# Assignment

1. create a random array of shape (6x6)
2. convert the array to an identity matrix

$$

I = 
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}

$$

$$

A.A^{-1} = A^{-1}.A = I

$$

In [1]:
def array_properties(a, label='a'):
    print(label, '= ')
    print(a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

In [3]:
# Q1 : Create a random array A, using randint seed 2 of shape (6x6)

import numpy as np

np.random.seed(2)

I = np.eye(6)
A = np.random.randint(1,10, (6,6))

In [5]:
# Q2 : Convert the array A, to an identity matrix I.

inverse_A = np.linalg.inv(A) 

# Dot product A . A-1
C = A @ inverse_A
C = np.round(C).astype(int) # round up the float & convert to int

# Position changed to A-1 . A
C2 = inverse_A @ A 
C2 = np.round(C2).astype(int)

print('I:\n', I)
print()
print('A @ inverse_A:\n', C)
print()
print('inverse_A @ A:\n', C)
print()

# Compare A.A-1 with identity matrix
print('A @ inverse_A == I:\n', C == I) 

# Compare A-1.A with identity matrix
print('\ninverse_A @ A == I:\n', C2 == I) 

I:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

A @ inverse_A:
 [[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

inverse_A @ A:
 [[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

A @ inverse_A == I:
 [[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]

inverse_A @ A == I:
 [[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [7]:
print('A:\n', A)
print('\nInverse of A:\n', inverse_A)

A:
 [[9 9 7 3 9 8]
 [3 2 6 5 5 6]
 [8 4 7 5 4 8]
 [7 2 4 6 9 5]
 [7 4 3 1 5 3]
 [5 2 8 9 3 9]]

Inverse of A:
 [[-0.11797753 -0.1011236   0.09430177  0.01163724  0.20987159  0.01203852]
 [ 0.2247191  -0.23595506 -0.4823435  -0.12760835  0.21589085  0.38523274]
 [-0.29213483  0.60674157 -0.49438202 -0.42696629  0.95505618  0.21348315]
 [ 0.04494382 -0.24719101 -0.53932584 -0.01123596  0.31460674  0.50561798]
 [ 0.01685393  0.15730337  0.04775281  0.12078652 -0.13202247 -0.18539326]
 [ 0.2247191  -0.23595506  1.0176565   0.37239165 -1.28410915 -0.61476726]]
